### ISSUE TITLE
Question about ISO support

### ISSUE THREAD

**Issue by ilyen85** [coseyfannitutti/discipline#11]
Hey Coseyfannitutti

First of all I would like to thank you for your fantastic work!

So my question, I missed the group buy on Friday, it was sold out when I managed to enter my details :( So I figured I will buy / create the necessary parts.

I have never did anything like this before so I have a couple of questions.
If I use a pcb manufacturing service, do I need anything else than the files in the gerber folder in this repo?

With these files will I be able to have an ISO compatible pcb?

Thank you again!

**Comment by mozaic-dev** [comment]
@ilyen85 yeah, there is even a picture of the white PCB showing off ISO enter

**Comment by coseyfannitutti** [comment]
Currently, no the ISO support and other changes for V2 are not yet in the repository. The version here only has ANSI compatibility.

I will be opening a larger pre-sale on Friday at 12PM US Eastern time to help meet some of the demand after they sold out so quickly last week.

I will be updating this repository with the ISO compatibility and other changes some time after that pre-sale has run.

**Comment by ilyen85** [comment]
Thank you! I will wait for that, I hope i will be able to grab a kit (or two) :)

Since I know that ISO compatibility is not yet in the repo I will close this issue
