### ISSUE TITLE
Discipline65 Case

### ISSUE THREAD

**Issue by jthoms1** [coseyfannitutti/discipline#12]
I was unsure about the colors you chose for the picture provided for the case.  It looks like you built those from Ponoko and used Lavender Acrylic and Cream Acrylic for the 2 x discpline-top2.

Is that correct? If so do you mind if I make a pull request to update your readme to give guidance to others looking to build those cases.

Oh those cases look amazing.

**Comment by coseyfannitutti** [comment]
Yes, that is correct.
