### ISSUE TITLE
Kit Plate and Foam

### ISSUE THREAD

**Issue by goranzarkovic** [coseyfannitutti/discipline#14]

**Comment by goranzarkovic** [comment]
resolved.

**Comment by Elkasitu** [comment]
@goranzarkovic did you find the .dxf? I'm also looking for a backplate that I can print myself

**Comment by jesusignazio** [comment]
@Elkasitu I think it is provided here https://github.com/coseyfannitutti/discipline/tree/master/case

**Comment by Elkasitu** [comment]
@jesusignazio From checking the files, the bottom case model seems to be for the full-acrylic case and is at least 15mm taller than the PCB.

The kit backplate seems to be the same size, the holes align with the PCB plus comes with extra holes for feet, here's a pic
![2020-06-21-181705_314x135_scrot](https://user-images.githubusercontent.com/4931545/85229710-c14da880-b3eb-11ea-8324-8b86d47f92ba.png)


@coseyfannitutti is there any way you could share the file for the backplate included in the kit?

**Comment by coseyfannitutti** [comment]
The bottom is already in the repository. In the gerber folder there are files for the bottom.

**Comment by Elkasitu** [comment]
Damn thanks, don't know how I missed that
