### ISSUE TITLE
Flashing Guide Links 404

### ISSUE THREAD

**Issue by jgrossmac** [coseyfannitutti/discipline#15]
Both Squarespace hosted flashing guides are returning a 404.

>`curl 'https://static1.squarespace.com/static/5c533d33348cd92b886e544d/t/5d90521b1d22d176452c44a5/1569739293092/DISCIPLINE+FLASHING+GUIDE.pdf' \
  -H 'authority: static1.squarespace.com' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-fetch-dest: document' \
  -H 'accept-language: en-US,en;q=0.9,ja;q=0.8' \
  --compressed`

**Comment by coseyfannitutti** [comment]
fixed and added VIA Configurator guide
