### ISSUE TITLE
Is the BOM parts list the same for the V2/ISO pcb? 

### ISSUE THREAD

**Issue by jesusignazio** [coseyfannitutti/discipline#20]
I would like to build the ISO version from the pcb, but since the source is not yet in this repository and the parts take a lot of time in delivery/shipping, I want to buy it to save time and to have it all when the PCB source is finally available.

Are all the parts the same for V2 compared to the BOM from the V1 pcb?

Thanks!

**Comment by coseyfannitutti** [comment]
V2 source has been published. The only difference in the BOM for V1 and V2 is one extra diode for ISO backslash/split left shift.

**Comment by jesusignazio** [comment]
THANKS!!
