### ISSUE TITLE
Step 12 in Build Guide says 4x standoffs, should be 6x

### ISSUE THREAD

**Issue by runasand** [coseyfannitutti/discipline#21]
Step 12 in the [Build Guide](https://static1.squarespace.com/static/5c533d33348cd92b886e544d/t/5e9fbf9e58f1fb0b01f71a7c/1587527585202/DISCIPLINE+BUILD+GUIDE.pdf) says:

> 4x M2 10+3mm standoffs (top acrylic)

I believe the correct version is:

> 6x M2 10+3mm standoffs (top acrylic)

**Comment by kilyn666** [comment]
In addition, atmega328p and 28 pin IC socket mentioned in the included components should actually be atmega32a and 40 pin IC socket

**Comment by coseyfannitutti** [comment]
Updated. Thanks.
