### ISSUE TITLE
Blinking LED?

### ISSUE THREAD

**Issue by DippedPretzels** [coseyfannitutti/discipline#27]
Just soldered a v2 from 2019, but it wasn't recognized in QMK toolbox after the boot and reset button sequence.  The LED just blinks at about 1 Hz.  My guess is it might be a problem with the usb port  soldering as it was done poorly, bit I didn't detect any obvious shorts.  What should the resistance be between the usb pads on the back?  Any idea what would cause a LED blinking?

**Comment by coseyfannitutti** [comment]
Well, the LED is not connected to the microcontroller at all. It is running directly off of USB power and pulled down with one of the 1.5K resistors, so you've almost definitely got an issue on your power and/or ground pins on the USB port or possibly the 4.7uF capacitor, which has a pretty tight pin pitch as well.
