### ISSUE TITLE
BOM Guide False

### ISSUE THREAD

**Issue by NiciTheNici** [coseyfannitutti/discipline#48]
There is an Error in the BOM. Comparing it to the [pdf build](https://static1.squarespace.com/static/5c533d33348cd92b886e544d/t/5f4597da4c8f740579aec0ca/1598396382120/DISCIPLINE+BUILD+GUIDE.pdf) guide there is a difference between the IC's used. In the BOM a ATMEGA32**P**-PU is mentioned under the Part column (the one for the discipad), this is wrong. What it should be is a ATMEGA32**A**-PU as mentioned in the Query column.

![image](https://user-images.githubusercontent.com/51826257/117211062-d57a7880-adf8-11eb-9575-b1db1dbb8ef5.png)

![image](https://user-images.githubusercontent.com/51826257/117211115-e4612b00-adf8-11eb-9ce7-ed43ad567af8.png)

This is a critical flaw for everyone using the BOM as it makes the end product unusable because of it.

**Comment by coseyfannitutti** [comment]
Fixed. Not sure how that changed, but I've changed it back.
