### ISSUE TITLE
Acrilic Guard DXF empty

### ISSUE THREAD

**Issue by paulus-michael** [coseyfannitutti/discipline#49]
Hi,

When i try to open acrylic-guard.dxf in inkscape or any online dxf viewer, i get the message that the file is empty.

Thanks a lot for your assistance!

**Comment by coseyfannitutti** [comment]
You need to download the entire Discipline repository to get the correct file. It sounds like you may have just right clicked the individual file and selected "save link as", which would result in saving as .dxf but with .html data.

**Comment by paulus-michael** [comment]
Thanks a lot, noobish issue solved :|
