### ISSUE TITLE
Screw type not clear

### ISSUE THREAD

**Issue by NiciTheNici** [coseyfannitutti/discipline#51]
The type of screws needed is not listed anywhere besides in the [build guide PDF](https://static1.squarespace.com/static/5c533d33348cd92b886e544d/t/5f4597da4c8f740579aec0ca/1598396382120/DISCIPLINE+BUILD+GUIDE.pdf) (page 4) 

I do not understand what type of screw is meant by ***6x M2 10+3mm standoffs***
I would think it means ***6x m2x10mm screws*** and ***6x 3mm standoffs*** but I am not sure.

![image](https://user-images.githubusercontent.com/51826257/117583802-7c1c8d00-b109-11eb-9aec-c2f213fef889.png)

**Comment by quark-works** [comment]
That's the correct name. The standoff you're looking for is the one in your picture:
![image](https://user-images.githubusercontent.com/20212610/118416122-bd65ed00-b673-11eb-851b-8258879fc4a1.png)

**Comment by omniphx** [comment]
10+3mm standoff = male-female
6mm standoff = female-female

**Comment by NiciTheNici** [comment]
Thank you, this helps a lot!
