### ISSUE TITLE
usb 3.0 vs 2.0

### ISSUE THREAD

**Issue by alkeeb** [coseyfannitutti/discipline#56]
I just burnt my 3rd board.

I am starting to think there is a problem with usb. Has anyone had problems with usb 3? does it supply too much current?

**Comment by coseyfannitutti** [comment]
No, there is not any issue with overcurrent inherently in the PCB design. The USB port used in the BOM, which is only USB 2.0 capable, as well as the pull down resistors on the CC pins should limit current to 5V/500mA.

**Comment by tifandev** [comment]
could you please post an update on the orders? people are starting to get pretty angry on  /mk and will start claims to their ccs
