### ISSUE TITLE
dxf file size when uploaded to ponoko

### ISSUE THREAD

**Issue by Ashtoruin** [coseyfannitutti/discipline#7]
![image](https://user-images.githubusercontent.com/5630219/74591209-bf26a800-500d-11ea-8697-546c82c84b03.png)

I was looking to do a run myself for me and a friend in the UK and figured I'd start by looking at Ponoko (since you suggested it for the cases) but when I upload the file for the discipline guard (I checked the Mysterium Guard + Nav also) I noticed that the sizes are way off. I'm assuming they're just scaled wrong and I need to manually override the size but you don't actually list what the sizes should be. I can probably figure it out myself but it would be nice if we had some values to sanity check against.

Judging from the size of the boards:
Discipline Guard: 304.9W?
Mysterium Guard: 347.7W?
Mysterium Nav: ?

**Comment by coseyfannitutti** [comment]
Manually entering 304.9 x 26.8 will get you the correct results.

There just seems to be issues with Ponoko's new auto detection system they recently launched.
The files were designed in mm and when measured in AutoCAD they show the correct size, and I'm not sure what would cause a scaling of one third, as mm to in would be either .04x or 25.4x.

Rest assured, though, if you manually enter those dimensions it will come out correct. I have be using them for a long time over several projects, and have never received an incorrectly sized piece.

Uploading it to other services shows it scaling correctly.
![image](https://user-images.githubusercontent.com/43188488/74697910-13768700-51ca-11ea-8923-9261deb20fbc.png)

**Comment by Ashtoruin** [comment]
Yeah, I actually opened them up in Fusion and double checked my sizes but I figured it might be nice to document this in the Readme or something for people wanting to print their own that aren't as familiar with CADD programs and such.

**Comment by coseyfannitutti** [comment]
I agree. I want to keep the main page as simple as possible, but I have added a note about manual dimension entry for Ponoko in the Readme for the case folders of Discipline and Mysterium.
