### ISSUE TITLE
Discipline inspired DIY Keyboard Troubleshooting

### ISSUE THREAD

**Issue by Steven2k6** [coseyfannitutti/discipline#70]
Hez, I designed and built a Keyboard, but I have some issues with the usbasp bootloader. When I connect the Keyboard to my pc, it says "Device Descriptor Request Failed" in the device-manager. I don't have the two zener diodes on my keyboard, are they the problem?
![schematic](https://user-images.githubusercontent.com/99575824/209571228-fadea8d5-20cc-4a88-a499-101e1fbda14a.png)
Edit: I use 3.3 instead of 5 volts, because I found out, that the keyboard doesn't work at all with 5 volts.

**Comment by NiciTheNici** [comment]
Heya, did you manage to fix this? I'm mildly interesting in designing my own keyboard in the future too and this seems rather important :)

**Comment by Steven2k6** [comment]
> Heya, did you manage to fix this? I'm mildly interesting in designing my own keyboard in the future too and this seems rather important :)

There where two 3.6V diodes missing on the data lines.
