### ISSUE TITLE
Version with split backspace?

### ISSUE THREAD

**Issue by ElectricCoffee** [coseyfannitutti/discipline#8]
Hi, love the design, I'm just wondering if you could also make a version of the PCB that has a split backspace?

That might sound strange at first, but it frees up room for the <code>`~</code> key, so it doesn't have to share space with <code>Esc</code>.

For an example of this in action, see the Sun Model 7:

![picture](https://i.stack.imgur.com/D8RsW.jpg)

**Comment by lstubbig** [comment]
A similar suggestion: I would love to see a version with split spacebars (2.75u 1.25u 2.25u). It's something really useful that practically no off-the-shelf keyboards offer. Would fit really well to the DIY character of the board and make it a definite buy for me.

**Comment by ElectricCoffee** [comment]
@lstubbig totally agree, a split spacebar would be neat for enabling an easy-to-reach extra custom bindable key. Though I fear finding half spacebars might be hard...

**Comment by lstubbig** [comment]
@ElectricCoffee Most keycap sets have an option for small spacebars nowadays (at least GMK and MT3 from Drop). You can also get relatively cheap XDA keycaps from Aliexpress.
@coseyfannitutti Would you be open to this? I don't have experience with KiCAD but if you give us some pointers maybe we can even add those features ourselves?

**Comment by ElectricCoffee** [comment]
@lstubbig for the spit spacebar I'd instead have it split into four 1.5u keys or maybe three 2u keys.
Something about the Romeo's wide-narrow-wide spacebar cluster looks wrong to me...

**Comment by mobin-amanzai** [comment]
@ElectricCoffee you could make a comprise sand share the left shift with the`~`` key

**Comment by savyexe** [comment]
> @ElectricCoffee Most keycap sets have an option for small spacebars nowadays (at least GMK and MT3 from Drop). You can also get relatively cheap XDA keycaps from Aliexpress.
> @coseyfannitutti Would you be open to this? I don't have experience with KiCAD but if you give us some pointers maybe we can even add those features ourselves?

hey, i know it's been months since you guys talked about this but i wanted to say that if you do end up doing a 2.75u 1.25u 2.25u split spacebar version and @coseyfannitutti gives you permission to place it as a sort of groupbuy i'd be interested
